apiVersion: v1
kind: ServiceAccount
metadata:
  name: agones-sdk
  namespace: k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agones-sdk-binding
  namespace: k8s
subjects:
  - kind: ServiceAccount
    name: agones-sdk
    namespace: k8s
roleRef:
  kind: ClusterRole
  name: agones-sdk
  apiGroup: rbac.authorization.k8s.io