apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/infra/namespace
  - ../../../base/infra/agones

labels:
  - pairs:
      env: local

images:
  - name: img-backend
    newName: api
    newTag: latest
