apiVersion: v1
kind: Service
metadata:
  name: spanner-emulator
spec:
  selector:
    app: spanner-emulator
  ports:
    - name: grpc
      protocol: TCP
      port: 9010
      targetPort: 9010
    - name: rest
      protocol: TCP
      port: 9020
      targetPort: 9020
