services:
  proxy:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: ollama-proxy
    ports:
      - "4000:4000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_API_BASE=http://host.docker.internal:11434
    #command: --model ollama/${__OLLAMA_MODEL} --alias ${__OLLAMA_MODEL} --port 4000
    command: --model ollama_chat/${__OLLAMA_MODEL} --alias ${__OLLAMA_MODEL} --port 4000
    restart: always
    networks:
      - ollama-net
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-base
    environment:
      - TZ=Asia/Tokyo
      - __OLLAMA_MODEL=${__OLLAMA_MODEL}
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama:ro
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
    networks:
      - ollama-net
  chat:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_BASE_URL=http://proxy:4000
      - OPENAI_API_KEY=dummy
      - DEFAULT_MODELS=${__OLLAMA_MODEL}
      # admin settings（Falseは大文字、WebUIが文字列で判断している模様（バグ））
      - WEBUI_AUTH=False
      - WEBUI_SECRET_KEY=any_random_string
      # comfyui settings
      - ENABLE_IMAGE_GENERATION=true
      - COMFYUI_BASE_URL=http://comfyui:8188
      - IMAGE_GENERATION_ENGINE=comfyui
      #- COMFYUI_WORKFLOW_FILE=/app/backend/comfyui_workflow.json
      ## local cache only
      - HF_HUB_OFFLINE=1
    depends_on:
      - proxy
    volumes:
      - open-webui:/app/backend/data
      #- ./comfyui-workflow.json:/app/backend/comfyui_workflow.json
    restart: always
    networks:
      - ollama-net
  comfyui:
    image: ghcr.io/ai-dock/comfyui:latest-cuda
    container_name: comfyui
    ports:
      - "8188:8188"
      - "1111:1111"
    environment:
      - WEB_ENABLE_AUTH=false
      - WEB_USER=guest
      - WEB_PASSWORD=guest
      - COMFYUI_SD_MODEL_NAME=${__COMFY_UI_MODEL}
    volumes:
      - ~/.comfyui/models:/opt/ComfyUI/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
    networks:
      - ollama-net
networks:
  ollama-net:
    driver: bridge
volumes:
  open-webui:
